### PR TITLE
Adding dedupe util

### LINKED ISSUE #34: Deduplication utility
It would be helpful to have a de-duplication utility that would read the `data.csv` and look for possible duplicate entries. One way of doing this would be to aggregate the rows by their `repository_name_unauthorized`, `st_city` and `state` and report on any where the count is > 1. It might also be useful to look at lon/lat values where they are available.

Reporting on them would be a good first step, but it may be that it should be able to optionally perform the edits with user input, which might be easier than having to use Excel.

### PR DESCRIPTION
**Pull request by edsu**
This new program `bin/dedupe.py` can inspect the `data.csv` dataset for duplicates. Duplicates are identified by identical values for `repository_name_unauthorized`, `st_city`, and `state`. It provides an editing interface for mediating the duplicates. You can start it by limiting to only edits made by a particular user:

```
bin/dedupe.py --entry-recorded-by 'Charlie Macquarie'
```

and can also ignore duplicates that are the result of records that have a PO Box and regular mailing address:

```
bin/dedupe.py --ignore-pobox
```

The editing interface allows you to move to the next/previous set of duplicates, to delete a record, to move a property from one record to another, undo a change and save the edits.

Screenshot 2023-08-11 at 12 42 26 PM

The installation of the dependencies now relies on poetry instead of pip, since it seems `pyproject.toml` seems like the future of Python packaging.

Closes #34

### CODE REVIEW

**Comment by edsu** [comment]
@helrond I took a pass at creating a Help page which describes the commands and provides some examples where needed. I also updated the code to highlight the last edit, which maybe is along the lines of what you were suggesting. Suggestions and pushed improvements are welcome!

Screenshot 2023-08-22 at 8 30 35 AM

**Comment by edsu** [comment]
A few remaining questions:

1. Should we create a new column `previous_ids` that records when records have been merged together? For example: suppose a user sees three potential duplicates with IDs A, B and C. The user decides to move some values from A and C into B and then deletes A and C. The `previous_ids` column in B is updated to include the comma separated list A,C.

2. Do we need a `date_entry_updated` column to record when the record was last updated?

**Comment by helrond** [comment]
Thanks Ed this looks great! I think those are great usability improvements.

Regarding your questions:
1. I guess this is kind of a philosophical question about whether we track changes in version control or in the data itself. Right now it's a bit of a mix of both (we have this in a VCS but we're also recording the names of people who added entries) so I think this is definitely an open question! My instinct would be that this particular use case may be better left to version control but that's not a strong opinion.
2. Yes, I think so!
3. I think that would be smart so we can ensure nothing breaks as dependency versions change? I haven't looked super closely at the internals but from what I did see it seems like it would be pretty easy to introduce some basic tests.

**Comment by edsu** [comment]
Ok, I'll add that `date_entry_updated` column as part of this commit. And will work on at least a basic test of the dedupe functionality.

Re: 1 I had the same thought as well about using VCS. But then I had second thoughts. So lets say someone had an old identifier A that was no longer in the dataset and we wanted to know what record it was merged into. I guess we could use [git bisect](https://git-scm.com/docs/git-bisect) to try to find the commit where A disappeared. Then we could look at other changes that happened at the same time and infer where it went? It should be fairly self explanatory, but there could be multiple changes that were made in the commit, so it might not be immediately obvious. If this sounds ok to you I think we can punt on it for now.

**Comment by helrond** [comment]
I think that's okay? If this data set starts to get a lot more attention and edits we can revisit.

**Comment by charliemacquarie** [comment]
@edsu finally got a chance to try this out again in:re the python version >=3.11 issue in poetry.lock, and this time `poetry install` worked without errors but when actually running `poetry run bin/dedupe.py` I get an ImportError trying to import the numpy dependencies for pandas. I wonder if it's because of the `python-versions = ">=3.9"` in poetry.lock? (noting that this still is all because I'm running an older python, for folks running more up to date versions it probably won't be a problem!)

**Comment by edsu** [comment]
@charliemacquarie what version of Python do you have? I guess there must have been an error that flew by when you did the `poetry install`?

**Comment by edsu** [comment]
I've added some tests for the `DedupeAnalyzer` that identifies duplicates, and also for `DedupeMediator` which allows the dataset to be edited (deleting records, copying properties, undoing changes, etc). They will run when commits are pushed to the repo (any branch) via a Github Action. Currently Python 3.8 and 3.11 are tested.

**Pull request merged**
