### PR TITLE
Add California Repositories

### PR DESCRIPTION
**Pull request by charliemacquarie**
This data was acquired by scraping the list of repositories that have contributed to the [California Revealed](https://californiarevealed.org/collections/list/institution) project of the California State Library. 

These repositories have not been de-duplicated against existing California Repositories. Charlie should come back and de-duplicate either manually or by comparing lat/long against existing repositories. 

Updates were made to data.csv. data.json and data.geojson used provided scripts bin/convert.py and bin/geojson.py.

### CODE REVIEW

**Comment by edsu** [comment]
Thanks for sending this @charliemacquarie! It's exciting to see the California Revealed data getting reused. It might be useful to talk this through with the larger group (@bmrgoldman, @tanseyem & @helrond) but what I would propose is that we merge this as is, and then we work separately on a utility that can look for duplicates in the `data.csv`?

Also, just an idea, but I wonder if it might helpful for us to have a directory that contains utilities for collecting information from different sources?

**Comment by charliemacquarie** [comment]
Thanks for helping me with this @edsu! I'll send another email this upcoming week to the whole group to check in about this, but I support this plan on action (merge as is, and then I will work on a utility that can look for duplicates in data.csv). 

I also like that idea of utilities for collecting information from different sources. (This means something that does basically what I just did right? I.e. you'd point the utility to your new .csv file with new repositories to add, and then the utility would add those to the data.csv file?) Let's talk about this in another meeting once I schedule one.

**Comment by edsu** [comment]
@charliemacquarie I ended up squashing your commits into a single commit, after I ran `bin/generate_ids.py` to assign identifiers to your new rows, and then`bin/convert.py` to convert them again to json and geojson. Unfortunately I thought when I merged these changes your PR would close automatically, but now it is flagged as having a conflict.

You should be able to see your new data has been added to `data.csv` here in https://github.com/RepoData/RepoData. But since you were working on the master branch you may need to create a new fork and local clone, since your master branch is now in conflict with RepoData/RepoData. 

Let me know if you want to chat about this if it's easier to walk through what happened here. Usually it is easier if you create changes on a branch and then submit a PR for that.

**Comment by charliemacquarie** [comment]
@edsu thanks for all the patience with me as I learn GitHub for repositories when people are _actually working_ on them! (besides just myself). 

I think I understand where the conflict arose, and this use case definitely makes me understand the value of making a new branch rather than forking the main branch. I ended up just deleting my local copy of the repo, "syncing" my fork (which just deleted my commits in charliemacquarie/RepoData and replaced them with the up-to-date RepoData/RepoData), and then re-cloning charliemacquarie/RepoData locally. 

I realized now that for working on a de-dupliicating utility I should probably make a new branch, so I'll do that in the coming days when I actually get some time to work on it. 

Thank you!

**Comment by edsu** [comment]
@charliemacquarie I'm glad you were able to figure it out. I don't know if you were thinking of using Pandas or not but I starting working here on something:

https://github.com/RepoData/RepoData/tree/t34-dedupe

**Pull request closed without merging**
